### ISSUE TITLE
roadmap of this project

### ISSUE THREAD

**Issue by deyituo** [collabora/WhisperSpeech#1]
Hi, There is roadmap for this project? I wonder if the project availabel recently?

**Comment by jpc** [comment]
Hey, we are working on this as we speak! :)

That said, even with pretrained models, this is a pretty big project and there are probably many unforeseen challenges ahead.

We'll keep updating the repo with more code and information as we progress with the implementation and training.

**Comment by jpc** [comment]
I've updated the issues and hopefully laid out a more complete roadmap that will help everyone track our progress.
