### ISSUE TITLE
Outdated RQBottleneckTransformer model

### ISSUE THREAD

**Issue by Subuday** [collabora/WhisperSpeech#118]
It looks like architecture of RQBottleneckTransformer has been changed, but model has not been retrained/reuploaded.
So trying to load RQBottleneckTransformer using 
`vq_model = vq_stoks.RQBottleneckTransformer.load_model(ref="collabora/whisperspeech:whisper-vq-stoks-medium-en+pl.model").cuda()` leads to error:
```
Error(s) in loading state_dict for RQBottleneckTransformer:
	Missing key(s) in state_dict: "rq.project_in.weight", "rq.project_in.bias", "rq.project_out.weight", "rq.project_out.bias". 
	Unexpected key(s) in state_dict: "rq.layers.0.project_in.weight", "rq.layers.0.project_in.bias", "rq.layers.0.project_out.weight", "rq.layers.0.project_out.bias".
```

**Comment by Subuday** [comment]
Okay, I was using incorrect version of vector_quantize_pytorch.
The correct fine is specified in `settings.ini` file.

**Comment by jpc** [comment]
Maybe we could do it when we start working on new languages @zoq ?
