### ISSUE TITLE
Run it on Mac - example

### ISSUE THREAD

**Issue by Grzegosz** [collabora/WhisperSpeech#125]
Would like to run it on Mac m1 - how to do it?
Is Mac version (saw other issue when it was merged) is released and can use pip to update WhisperSpeach? If no - how to build it locally?
Anyone can share script to generate voice on MacBook? Thank you.

**Comment by jpc** [comment]
It should work out of the box with the pip package. Both the notebook and the scripts on the example folder.

**Comment by Grzegosz** [comment]
Thanks.
