### ISSUE TITLE
sorry but request steps help

### ISSUE THREAD

**Issue by FlyToYourMooN** [collabora/WhisperSpeech#15]
There are a lot of jupyter notebooks here, and I'm not very clear what the steps to train a model are...

**Comment by jpc** [comment]
Hey, yeah, sorry about that. There were a lot of experiments which I wanted to preserve for posterity (so people don't repeat my mistakes) but they did obscure the "happy path" a lot.

I am in the process of cleaning up the code and turning a lot of it into modular libraries (separate training and models, integrating PyTorch Lightning support for multiGPU training) which should help navigate it a lot. I will finish it this week.

**Comment by FlyToYourMooN** [comment]
thank you!!!

**Comment by jpc** [comment]
The refactoring is now mostly complete (apart from the semantic token extraction model which we plan to refactor soon) and we prepared an inference notebook which shows how the pipeline works.

I'll close this issue but if you still have question I am happy to reopen and discuss them further.
