### ISSUE TITLE
Model Share

### ISSUE THREAD

**Issue by talipturkmen** [collabora/WhisperSpeech#25]
Hello,  

Thank you for this great work. With latest commits I've seen that you didn't push the checkpoints. I want to try the semantic token extractor. Is there any way to access to the latest models?

Kind regards

**Comment by jpc** [comment]
Hey, thanks a lot. The [models](https://huggingface.co/collabora/whisperspeech) and [datasets](https://huggingface.co/datasets/collabora/whisperspeech) are now uploaded on huggingface. I’ll update the README with direct links, thanks for pointing it out.

**Comment by talipturkmen** [comment]
Thank you so much 🙏
