### ISSUE TITLE
e2e inference results

### ISSUE THREAD

**Issue by mayfool** [collabora/WhisperSpeech#26]
Thanks for sharing the model. However, I try to inferenc use the trained model, the generated audio is all white noise. I just follow you inference scripts with nothing changed. It seems strange.

**Comment by jpc** [comment]
Hey, that's quite surprising. I am testing the inference notebook on my 4090 and on Google Colab T4. Would you mind sharing what platform are you running this on?

Also could you show the output of `pip install WhisperSpeech`? Maybe it would shine some light on the problem?

**Comment by mayfool** [comment]
I run the inference code on V100. Things runs normally, but I can't get the correct audios..

**Comment by jpc** [comment]
Hey, have you tried the default prompt? I’ve noticed an issue with short texts in #24 . I am preparing a fixed model that I should release tomorrow but in the mean time a workaround would be to generate speech length close to the full 30 second window size.

**Comment by mayfool** [comment]
Yes，I used the default prompt text ，also used part of the prompt text. The results seems the same, all white noise，and the length of the generated audio.

**Comment by zoq** [comment]
I tested the notebook with the default prompt and the generated output is fine. However, I can reproduce the result with a shorter sentence, e.g. I was running:

```python
pipe.generate_to_notebook("""
Collabora is a global private company headquartered in Cambridge, United Kingdom, with offices in Cambridge and Montreal. It provides open-source consultancy, training and products to companies.
""")
```

which produces noise, but if I triple the length:

```python
pipe.generate_to_notebook("""
Collabora is a global private company headquartered in Cambridge, United Kingdom, with offices in Cambridge and Montreal. It provides open-source consultancy, training and products to companies.
Collabora is a global private company headquartered in Cambridge, United Kingdom, with offices in Cambridge and Montreal. It provides open-source consultancy, training and products to companies.
Collabora is a global private company headquartered in Cambridge, United Kingdom, with offices in Cambridge and Montreal. It provides open-source consultancy, training and products to companies.
""")
```

the pipeline generates the expected audio. So I think, as @jpc mentioned, the pipeline currently only works on longer text. @mayfool since you said you used longer sentences/text, do you mind to post the example, so we can try to reproduce the issue on our side?

**Comment by mayfool** [comment]
![image](https://github.com/collabora/WhisperSpeech/assets/11803563/604ff3f0-ab8e-42b2-ac37-01fed2e3ea28)
Generated files produced by
```
pipe.generate_to_notebook("./test.wav",
"""
Collabora is a global private company headquartered in Cambridge, United Kingdom, with offices in Cambridge and Montreal. It provides open-source consultancy, training and products to companies.
Collabora is a global private company headquartered in Cambridge, United Kingdom, with offices in Cambridge and Montreal. It provides open-source consultancy, training and products to companies.
Collabora is a global private company headquartered in Cambridge, United Kingdom, with offices in Cambridge and Montreal. It provides open-source consultancy, training and products to companies.
""")
```

**Comment by jpc** [comment]
Hey,

I think for what you want to achieve it would be better to use the `pipe.generate_to_file` function instead of `pipe.generate_to_notebook`.

The example you posted tries to speak "./test.wav" with a very strange speaker id (the long text). I have to look into why it does not raise a helpful error.

**Comment by mayfool** [comment]
> pipe.generate_to_notebook("./test.wav",
> """
> Collabora is a global private company headquartered in Cambridge, United Kingdom, with offices in Cambridge and Montreal. It provides open-source consultancy, training and products to companies.
> Collabora is a global private company headquartered in Cambridge, United Kingdom, with offices in Cambridge and Montreal. It provides open-source consultancy, training and products to companies.
> Collabora is a global private company headquartered in Cambridge, United Kingdom, with offices in Cambridge and Montreal. It provides open-source consultancy, training and products to companies.
> """)
My inference code is 
```
pipe.generate_to_file("./test.wav",
"""
Collabora is a global private company headquartered in Cambridge, United Kingdom, with offices in Cambridge and Montreal. It provides open-source consultancy, training and products to companies.
Collabora is a global private company headquartered in Cambridge, United Kingdom, with offices in Cambridge and Montreal. It provides open-source consultancy, training and products to companies.
Collabora is a global private company headquartered in Cambridge, United Kingdom, with offices in Cambridge and Montreal. It provides open-source consultancy, training and products to companies.
""")
```

**Comment by jpc** [comment]
I am afraid I cannot reproduce the issue you are seeing at all, neither in Colab nor locally in Jupyter on a 4090. :(

Would you mind trying this in Google Colab (the free `T4` GPU instance is enough, even if a bit slow) to ensure a reproducible environment? You'd have to use `generate_to_notebook` there since the links to local files do not work in Colab.

**Comment by mayfool** [comment]
> I am afraid I cannot reproduce the issue you are seeing at all, neither in Colab nor locally in Jupyter on a 4090. :(
> 
> Would you mind trying this in Google Colab (the free `T4` GPU instance is enough, even if a bit slow) to ensure a reproducible environment? You'd have to use `generate_to_notebook` there since the links to local files do not work in Colab.

Thanks for reply.I will try as you say.Hope it will work.

**Comment by jpc** [comment]
Hey, we have recently released much better models so I am pretty sure this should not be happening. If you still encounter this problem with the new models then please feel free to reopen the issue.
