### ISSUE TITLE
Question about semantic tokens extraction

### ISSUE THREAD

**Issue by asr-pub** [collabora/WhisperSpeech#28]
Hello, I read the script (`2C. Whisper semantic embedding extraction.ipynb` and `2F. Residual (RQ) semantic token extraction model.ipynb`) about semantic token extraction, and I have a few questions. I would like to discuss them with you.

1. Is there a mistake in the image, because I cannot find the `encode` method in vqmodel.
![image](https://github.com/collabora/WhisperSpeech/assets/22003430/f16ef40c-93e3-4285-ad3d-ae46cf27660b)

2. Do you measure the Speak Infomation in the Whisper encoder's embedding after you add the RVQ ? Maybe the semantic tokens still have much Speaker Infomation.

**Comment by jpc** [comment]
Hey, sorry about that – I have not updated the 2C and 2F notebooks yet after refactoring the inference code. Your inference is correct – the old `encode` method got renamed to `quantize`.

We can successfully use the same semantic tokens to synthesize multiple speakers – that suggests that we drop most of the speaker information. The distillation process also only cares about text which does not require speaker info so the bottleneck should drop anything that is not crucial.

OTOH the semantic tokens do carry prosody (tempo – for sure, probably also intonation). This is something that would be great to quantify.

**Comment by asr-pub** [comment]
OK, I will use your code to train a English-Mandarin Mixed vq-model, and compare this model and the HuBERT.

**Comment by jpc** [comment]
Hey, if you want to do some research around how these codes work then I would love to collaborate on it.

If you just want to benchmark them against HuBERT it may make sense to wait a few days because I am planning to do some refactoring and optimization of the semantic token model this week.

**Comment by jpc** [comment]
The current semantic token model is a lot better than the old one and supports English and Polish. We currently use 512 codes at 25 tokens per second.
