### ISSUE TITLE
Request for Data Usage Permission

### ISSUE THREAD

**Issue by Yongxin-Zhu** [collabora/WhisperSpeech#29]
Hi, excellent work! I am interested in using the data from this repository [Huggingface](https://huggingface.co/datasets/collabora/whisperspeech/tree/main) for academic research purposes. However, I noticed that there is no license information provided. Could you please clarify whether the data in this repository is available for reuse, and if so, under what terms and conditions?

Thank you for your assistance in clarifying the usage rights for this data.

Sincerely,

**Comment by jpc** [comment]
Hey, thanks for reaching out and sorry I forgot to fill in the license info. The dataset is 100% derived from LibriLight and we are releasing the processed data under the same terms – Public Domain.

The Encodec acoustic tokens are as good as they’ll get. For the semantic tokens, we are working on improving them right now so we’ll likely update them in a week or two.

If you use it we would love if you could give us a boost by pointing at this repo but that’s not a requirement.
