### ISSUE TITLE
Colab Demo appears to be broken - libcuda.so not found

### ISSUE THREAD

**Issue by HazySkies** [collabora/WhisperSpeech#46]
Full error:

```
[2024-01-18 16:33:36,920] [0/0] torch._dynamo.variables.torch: [WARNING] Profiler function <class 'torch.autograd.profiler.record_function'> will be ignored

---------------------------------------------------------------------------

BackendCompilerFailed                     Traceback (most recent call last)

[<ipython-input-7-8f3d1d1ad737>](https://localhost:8080/#) in <cell line: 3>()
      1 # this is very slow right now since our inference code is not very optimized
      2 # but even without this crucial optimization it is still better than real-time on an RTX 4090
----> 3 pipe.generate_to_notebook("""
      4 This is the first demo of Whisper Speech, a fully open source text-to-speech model trained by Collabora and Lion on the Juwels supercomputer.
      5 """)

52 frames

[/usr/lib/python3.10/concurrent/futures/_base.py](https://localhost:8080/#) in __get_result(self)
    401         if self._exception:
    402             try:
--> 403                 raise self._exception
    404             finally:
    405                 # Break a reference cycle with the exception in self._exception

BackendCompilerFailed: backend='inductor' raised:
AssertionError: libcuda.so cannot found!


Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
```

Hoping this is fixed soon. WhisperSpeech so far is sounding quite promising, and I'm eager to test it further, preferably through a typically reliable and less locally resource intensive method like Colab. Also, partly because I have many other AI installed already and have a tendency to accidentally break things when adding another, haha.

**Comment by HazySkies** [comment]
> See https://github.com/collabora/WhisperSpeech/issues/43 for a solution.
Ah, thank you. Tried it but it seems to have generated another issue on a later step.
`---------------------------------------------------------------------------

RuntimeError                              Traceback (most recent call last)

[<ipython-input-8-33b66061c992>](https://localhost:8080/#) in <cell line: 3>()
      1 # this is very slow right now since our inference code is not very optimized
      2 # but even without this crucial optimization it is still better than real-time on an RTX 4090
----> 3 pipe.generate_to_notebook("""
      4 This example uses the default model of Whisper Speech. More specifically S 2 A hyphen Q 4 hyphen tiny, english and polish model. This will then be passed into RVC to achieve a potentially cleaner result.
      5 """)

9 frames

[/usr/local/lib/python3.10/dist-packages/whisperspeech/modules.py](https://localhost:8080/#) in unembed(self, embs)
    317     def unembed(self, embs):
    318         if not self.training and self.merged_out is not None:
--> 319             return F.linear(embs, self.merged_out, self.bias_out) # embs @ self.merged_out + self.bias_out
    320 
    321         orig_embs = embs

RuntimeError: self and mat2 must have the same dtype, but got Float and Half`

**Comment by jpc** [comment]
Hey, thanks for noticing this and reaching out. I released an updated version without `torch.compile` that should work in Colab.
