### ISSUE TITLE
ImportError when installing locally

### ISSUE THREAD

**Issue by fakerybakery** [collabora/WhisperSpeech#54]
Hi,
I'm trying to install the package locally. I cloned the git repository and installed it w/ pip, however when running it I get the following error:
```
ImportError: cannot import name 'languages' from 'whisperspeech'
```

**Comment by fakerybakery** [comment]
In the pip package, I see that a file called `languages.py` exists, however this file is not in the Git repo

**Comment by jpc** [comment]
Good catch, thanks. Pushed a fix.
