### ISSUE TITLE
Response time - how fast is it?

### ISSUE THREAD

**Issue by rvsh2** [collabora/WhisperSpeech#60]
Is it normal that on rtx 3080ti it takes from 2 seconds for two word sentence to get response to even 30 seconds for 40 word sentence?

I used this mockup to test:

```
import torch
import torchaudio
from whisperspeech.pipeline import Pipeline
import io
import sounddevice as sd
import time
pipe = Pipeline(s2a_ref='collabora/whisperspeech:s2a-q4-base-en+pl.model')
output = io.BytesIO()
print(torch.cuda.is_available())
while True:

	input1 = input("Powiedz: ")
	start_time = time.perf_counter()
	output.seek(0)

	pipe.generate_to_file(output, input1, lang='pl')
	output.seek(0)
	stop_time = time.perf_counter()
	print(f"Processing took {stop_time - start_time:0.4f} seconds")
	waveform, sample_rate = torchaudio.load(output)
	audio_numpy = waveform.numpy()
	sd.play(audio_numpy[0], 24000)
	sd.wait()
```

Powiedz: Napisz coś ciekawszego.
Processing took 4.5448 seconds

Powiedz: Sprwadzamy czas odpowiedzi. Czy czas będzie krótki czy długi? Jak szybko zareaguje? Bardzo fajny model o sporych możliwościach.
Processing took 19.0766 seconds

To run this mockup i had to change line 36 i a2wav.py
from
```
        torchaudio.save(fname, audio.cpu(), 24000)
```
to
```
        torchaudio.save(fname, audio.cpu(), 24000, format="wav")
```

Maybe there is a simpler way but this is what I could do.

**Comment by jpc** [comment]
Hi, have you tried passing `torch_compile=True` to `Pipeline`?

I disabled it by default since it seemed to cause issues in Colab and makes the first inference a lot slower but it should make subsequent generations more than 5x faster.
