### ISSUE TITLE
[Question]Any demo?

### ISSUE THREAD

**Issue by OnceJune** [collabora/WhisperSpeech#8]
Hi, thanks for your great work, could you share the demo audio from this code?

**Comment by jpc** [comment]
In the end we should achieve this level of quality: https://google-research.github.io/seanet/speartts/examples/

Right now we are validating the whole pipeline before we train bigger models on more data so the output is not very pleasant (I've committed some work-in-progress wav files to the repo today). These tests show that the Whisper embeddings are a good replacement for the w2v-BERT-derived tokens but we still have quite a few bugs to fix.

**Comment by jpc** [comment]
It took a while to get there but the demo is now available on Google Colab: [![Test it out yourself in
Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/collabora/WhisperSpeech/blob/main/Inference%20example.ipynb)
