### ISSUE TITLE
Update readme to show speed/tokens per second

### ISSUE THREAD

**Issue by BBC-Esq** [collabora/WhisperSpeech#90]
Now that we have CUDA, basic MPS support, and CPU support...Is it possible to create a table or something on the github readme showing the speed.  Initially it'll be scant, but eventually once it improves it'll be a source of comparison to others like Bark etc.

**Comment by jpc** [comment]
That's a good idea, I have a benchmark script we could adapt for that.

**Comment by BBC-Esq** [comment]
Ooh, can I have the script for my own testing?  ;-)
